### ISSUE TITLE
NavItem active states are incorrect with PureComponent

### ISSUE THREAD

**Issue by ecoleman** [tabler/tabler-react#226]
Not sure if this is a bug or I am doing something wrong...

`NavItem` is currently a `PureComponent`. When combined with react-router in my app, the active state gets set on the initial page load, and will never change.

If I change NavItem to a regular `Component`, the route changes and active states are reflected properly.

**Comment by jonthomp** [comment]
Thanks for the report I'll look into this and see what's going on, must be a bug of sorts

**Comment by jonthomp** [comment]
@ecoleman how were you trying to do this, using the `NavItem` `LinkComponent` prop or just wrapping the `NavItem` in a RR `Link` component?

**Comment by ecoleman** [comment]
I do the following:

`js
const navBarItems: Array<NavItem> = [
  {
    value: 'Dashboard',
    to: '/dashboard',
    icon: 'home',
    LinkComponent: NavLink,
  },
  {
    value: 'Example List',
    to: '/examples',
    icon: 'home',
    LinkComponent: NavLink,
  },
]

const App = () => (
  <SiteWrapper navItems={navBarItems}>
    <Switch>
      <Redirect exact from="/" to="/dashboard" />
      <Route path="/dashboard" exact component={Dashboard} />
      <Route exact path="/examples" component={ExampleList} />
    </Switch>
  </SiteWrapper>
)

export default (
  <ApolloProvider client={apolloClient}>
    <UserProvider value={this.state.userData}>
      <BrowserRouter>
        <App>
      </BrowserRoute>
    </UserProvider>
</ApolloProvider>  
)`

**Comment by jonthomp** [comment]
@ecoleman if you wrap the `NavLinks` with RRs withRouter HOC it should solve the issue

**Comment by ecoleman** [comment]
The `withRouter` thing still doesn't seem to solve the problem for me. 

Is there an actual reason/performance issue for NavItem being a pure component?

**Comment by jonthomp** [comment]
Nope I don't think so, I'll change it now
