### ISSUE TITLE
TablerLoginPage logo documentation

### ISSUE THREAD

**Issue by jayb967** [tabler/tabler-react#467]
I was not able to find documentation on changing the logo and/or removing in meantime for the login template. In docs it is also shown like this: 
![Screen Shot 2019-06-22 at 3 08 57 PM](https://user-images.githubusercontent.com/23585399/59969378-c9d18180-9500-11e9-9911-071876a34b0f.png)

Is this possible?

**Comment by ronaldaraujo** [comment]
I am also the same question.

**Comment by diegodorado** [comment]
this seems to be hardcoded in the template...

**Comment by jonthomp** [comment]
This has been resolved in the version 2 alpha

`npm install tabler-react@alpha`
`yarn add tabler-react@alpha`

**Comment by franva** [comment]
hi @jonthomp  I git cloned the master branch and I am still seeing the hardcoded logo. Could you please show me how did you fix it?
